services:
  agentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: zeye-agentdvr
    restart: unless-stopped
    privileged: true
    environment:
      PUID: "0"
      PGID: "0"
      TZ: "Asia/Bangkok"
      AGENTDVR_WEBUI_PORT: "8090"
    ports:
      - "9292:8090"
      - "3478:3478/udp"
      - "50000-50100:50000-50100/udp"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
    device_cgroup_rules:
      - "c 81:* rmw"
    volumes:
      - "/opt/zeye/config:/AgentDVR/Media/XML"
      - "/opt/zeye/media:/AgentDVR/Media/WebServerRoot/Media"
      - "/opt/zeye/commands:/AgentDVR/Commands"

networks:
  default:
    name: zeye_default
