import os
import stat

files = {
    "docs/AI_SETUP.md": """# Built-in AI Setup

Agent DVR supports integrated AI for object recognition, face detection, and plate reading.
**Note:** Some built-in AI features or push notifications generated by AI require a valid iSpyConnect Pro subscription.

## Recommendations for Stability

1. **Start Small**: Begin by enabling AI on a **single camera** only.
2. **Low Sampling**: Configure the AI sampling rate to evaluate only 1 or 2 frames per second. High framerate AI analysis will quickly overwhelm most systems.
3. **Decoder Default**: Leave the Agent DVR video decoder set to **CPU** until your single-camera AI setup proves stable. Do not attempt to force GPU acceleration immediately.
4. **Manual Model Management**: Do not auto-install external AI models. All necessary models should be managed exclusively through the Agent DVR web interface.
""",
    "docs/RTMP_STREAMING.md": """# RTMP Streaming

Agent DVR allows you to push or pull RTMP streams. This is useful for streaming your CCTV feed to external platforms.
**Note:** RTMP broadcasting functionality natively requires an active Agent DVR Pro license.

## Configuration Warnings

1. Obtain your RTMP Stream URL and Stream Key from your broadcast platform.
2. Store your stream key safely in `.env.pro` under `RTMP_STREAM_KEY`.
3. Configure the Agent DVR interface directly using your credentials.
4. **CRITICAL:** Never commit your stream key or `.env.pro` file to any git repository!
""",
    "docs/HD_4K_PLAYBACK.md": """# HD and 4K Playback

Deploying high-resolution HD (1080p) or 4K (2160p) cameras drastically changes system requirements.
**Note:** Native HD/4K web playback and remote streaming optimization features require an iSpyConnect Pro license.

## Infrastructure Constraints

- **CPU / GPU**: 4K encoding and decoding requires significant computational power. If GPU acceleration is not perfectly configured or supported by your hardware, 4K streams will cause severe CPU throttling and latency.
- **Network**: Ensure your local gigabit network can handle the sustained bandwidth required for multiple 4K cameras. Wi-Fi cameras are highly discouraged for 4K.
- **Storage**: High-resolution video will fill your storage drives exponentially faster. Ensure you have massive HDD space mapped to `/opt/zeye/media` or aggressive storage retention policies enabled.
- **Validation**: Before scaling up, run `./scripts/resource-check.sh` to ensure your system isn't already buckling under the load.
""",
    "scripts/resource-check.sh": """#!/bin/bash
set -e

echo "=== System Resource Diagnostic Tool ==="
echo ""

echo "[ Uptime ]"
uptime
echo ""

echo "[ CPU Cores Available ]"
nproc
echo ""

if command -v lscpu >/dev/null 2>&1; then
    echo "[ CPU Architecture Summary ]"
    lscpu | grep -E "^(Model name|Architecture|CPU\\(s\\)|Thread\\(s\\) per core|Core\\(s\\) per socket|Socket\\(s\\))" || true
    echo ""
fi

echo "[ System Memory ]"
free -h
echo ""

echo "[ Storage Availability (/opt/zeye) ]"
df -h /opt/zeye 2>/dev/null || df -h /
echo ""

echo "[ Docker Container Stats (zeye-agentdvr) ]"
if docker ps --format '{{.Names}}' | grep -q "^zeye-agentdvr$"; then
    docker stats --no-stream zeye-agentdvr
else
    echo "zeye-agentdvr container is NOT currently running!"
fi
echo ""
echo "======================================="
"""
}

for path, content in files.items():
    full_path = os.path.join("/home/zeazdev/zeye", path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w") as f:
        f.write(content)
    if full_path.endswith(".sh"):
        os.chmod(full_path, os.stat(full_path).st_mode | stat.S_IEXEC)
